Repository 3DAsset-eCommerce/3D-FE, pull requests merged in 2023-07, with the labels that each got.

#136 feat: 카테고리 에셋 수정
  package.json
  src/api/service/asset.ts
  src/app/categories/[...slug]/page.tsx
  src/app/categories/page.tsx
  src/app/page.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assetDetail/ReviewItem.tsx
  src/components/assets/AssetItem.tsx
  src/components/assets/CategoryByAsset.tsx
  src/components/assets/IndividualAsset.tsx
  src/components/category/CategoryAssetList.tsx
  src/components/common/Drawer.tsx
  src/components/common/Rating.tsx
  src/components/common/SideNav/CategoryAsset.tsx
  src/components/common/SideNav/CategoryList.tsx
  src/components/common/SideNav/SideNav.tsx
  src/components/myAsset/MyAsset.tsx
  src/data/category.json
  src/hooks/useGetAssets.ts
  src/mocks/handlers.ts
  src/mocks/loginInfo.json
  src/mocks/logout.json
  src/mocks/server.ts
  src/mocks/users.json
Labels: Type: Bug

#144 feat: 메인페이지 - 카데고리 기능 수정 및 추가 병합
  package.json
  src/app/categories/[...slug]/page.tsx
  src/app/categories/page.tsx
  src/app/page.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assets/AssetItem.tsx
  src/components/assets/CategoryByAsset.tsx
  src/components/assets/IndividualAsset.tsx
  src/components/category/CategoryAssetList.tsx
  src/components/common/Drawer.tsx
  src/components/common/SideNav/CategoryAsset.tsx
  src/components/common/SideNav/CategoryList.tsx
  src/components/common/SideNav/SideNav.tsx
  src/hooks/useGetAssets.ts
  src/mocks/handlers.ts
  src/mocks/loginInfo.json
  src/mocks/logout.json
  src/mocks/server.ts
  src/mocks/users.json
Labels: Type: Enhancement

#145 feat: :sparkles: 카테고리 수정
  src/data/category.json
Labels: Priority: Medium, Type: Bug

#147 feat: 카테고리 및 결제페이지 기능 추가
  src/api/interface/auth.ts
  src/api/interface/cart.ts
  src/api/interface/payment.ts
  src/api/service/myPage.ts
  src/api/service/payments.ts
  src/components/cart/Cart.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItem.tsx
  src/components/common/header/Header.tsx
  src/components/logout/Logout.tsx
  src/components/payment/OrderInfo.tsx
  src/components/payment/Payment.tsx
  src/components/payment/PaymentItem.tsx
  src/components/payment/complete/CompleteItem.tsx
  src/components/payment/complete/CompleteTable.tsx
  src/components/wishList/TableItem.tsx
  src/data/category.json
  src/hooks/useMyPage.ts
  src/hooks/useUser.ts
  src/utils/cartUtils.ts
  src/utils/paymentUtils.ts
Labels: Type: Enhancement

#150 feat: 이미지 출력 오류 기능 수정
  package.json
  public/icons/cameraOff.svg
  src/api/service/asset.ts
  src/app/categories/page.tsx
  src/app/page.tsx
  src/components/assets/AssetItem.tsx
  src/components/assets/AssetList.tsx
  src/components/assets/CategoryByAsset.tsx
  src/components/assets/IndividualAsset.tsx
  src/components/category/CategoryAssetContainer.tsx
  src/components/category/CategoryAssetList.tsx
  src/hooks/useGetAssets.ts
  yarn.lock
Labels: Priority: High, Type: Enhancement, Category: Backend(API DB), Category: Frontend(JS CSS)

#151 feat: 이미지 안보이는 오류 수정
  next.config.js
  package.json
  src/api/axios.ts
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assets/AssetItem.tsx
  src/components/common/SideNav/Tags.tsx
  src/components/common/threeModel/ThreeModel.tsx
  yarn.lock
Labels: Type: Bug

#152 feat: 이미지 출력 오류 수정 및 three.js반영
  next.config.js
  package.json
  src/api/axios.ts
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assets/AssetItem.tsx
  src/components/common/SideNav/Tags.tsx
  src/components/common/threeModel/ThreeModel.tsx
  yarn.lock
Labels: Type: Enhancement, Category: Backend(API DB)

#153 feat: 헤더 수정 및 장바구니 담기 기능
  public/icons/tip.svg
  src/api/interface/cart.ts
  src/api/service/cart.ts
  src/components/assetDetail/AssetDetailAddCart.tsx
  src/components/cart/CartItem.tsx
  src/components/common/Drawer.tsx
  src/components/common/Toast.tsx
  src/components/common/header/Header.tsx
  src/components/login/Login.tsx
  src/hooks/useUser.ts
Labels: Status: Available, Status: In Progress, Priority: High, Category: Frontend(JS CSS)

#146 feat: Mypage 주문 상세내역 기능수정
  src/api/interface/payment.ts
  src/api/service/myPage.ts
  src/app/my-page/orderHistory/page.tsx
  src/components/common/header/Header.tsx
  src/components/myPage/orderHistory/MyOrderHistory.tsx
  src/components/myPage/orderHistory/MyOrderHistoryItem.tsx
  src/components/myPage/orderHistory/MyOrderHistoryList.tsx
  src/components/myPage/orderHistory/OrderHistoryDrawer.tsx
  src/components/myPage/orderHistory/calendar/MyOrderCalendar.tsx
  src/components/myPage/orderHistory/orderHistoryDetail/DetailDrawer.tsx
  src/components/myPage/orderHistory/orderHistoryDetail/DetailList.tsx
  src/components/myPage/orderHistory/orderHistoryDetail/DetailListItem.tsx
  src/components/myPage/orderHistory/orderHistoryDetail/MyOrderDetail.tsx
  src/components/myPage/setting/MyAccountSetting.tsx
  src/hooks/useMyPage.ts
  src/store/clickedOrderHistorySlice.tsx
  src/store/orderHistoryStore.ts
  src/store/store.ts
Labels: Priority: Medium, Type: Enhancement, Category: Backend(API DB)
