Repository 3DAsset-eCommerce/3D-FE, pull requests merged in 2023-06, with the labels that each got.

#21 feat: Asset detail 페이지 레이아웃 구현
  src/api/assets.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/assetDetail/AssetDetail.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assetDetail/AssetDetailNav.tsx
  src/components/assetDetail/AssetDetailWishlist.tsx
  src/components/assets/AssetTags.tsx
  src/components/common/Drawer.tsx
  src/components/common/WishlistButton.tsx
  src/data/assets.json
  src/styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: Priority: Medium

#22 feat: AssetDetail merge
  src/api/assets.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/assetDetail/AssetDetail.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assetDetail/AssetDetailNav.tsx
  src/components/assetDetail/AssetDetailWishlist.tsx
  src/components/assets/AssetTags.tsx
  src/components/common/Drawer.tsx
  src/components/common/WishlistButton.tsx
  src/data/assets.json
  src/styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: Status: Review Needed, Priority: Medium, Type: Enhancement, Category: Frontend(JS CSS)

#23 feat: :sparkles: 목업 데이터 세팅
  package.json
  src/mocks/handlers.ts
  src/mocks/loginInfo.json
  src/mocks/logout.json
  src/mocks/server.ts
  src/mocks/users.json
  yarn.lock
Labels: Status: Review Needed, Priority: Medium, Type: Enhancement, Category: Backend(API DB), Category: Frontend(JS CSS), Category: Test

#29 feat: asset categories key 추가
  src/components/assetDetail/AssetDetailNav.tsx
  src/store/clickedAssetSlice.tsx
  yarn.lock
Labels: Type: Bug, Category: Test

#30 release: develop merged for deploy
  src/components/assetDetail/AssetDetailNav.tsx
  src/store/clickedAssetSlice.tsx
  yarn.lock
Labels: Type: Bug, Category: Test

#32 feat: Login
  public/google.svg
  src/app/login/page.tsx
  src/components/login/Login.tsx
Labels: Status: Completed, Priority: High, Type: Enhancement, Category: Frontend(JS CSS)

#40 feat: TermModal UI 퍼블리싱
  src/components/signup/SignUp.tsx
  src/components/signup/TermsModal.tsx
Labels: Status: Completed, Priority: High, Type: Enhancement, Category: Frontend(JS CSS)

#43 feat: layout 1차 UI 퍼블리싱
  public/icons/list.svg
  public/logo-title.svg
  src/api/category.ts
  src/components/common/Category.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/SideNav.tsx
  src/data/category.json
  src/interface/category.ts
  src/store/setSelectedCategory.tsx
  src/store/store.ts
  src/styles/globals.css
  tailwind.config.js
Labels: Status: In Progress, Priority: High, Type: Enhancement, Category: Frontend(JS CSS)

#47 Develop
  public/icons/list.svg
  public/logo-title.svg
  src/api/category.ts
  src/components/common/Category.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/SideNav.tsx
  src/components/signup/SignUp.tsx
  src/components/signup/TermsModal.tsx
  src/data/category.json
  src/interface/category.ts
  src/store/setSelectedCategory.tsx
  src/store/store.ts
  src/styles/globals.css
  tailwind.config.js
Labels: Status: Completed, Priority: High, Type: Enhancement, Category: Frontend(JS CSS)

#48 feat: ✨ prettier plugin tailwind css 적용
  .prettierrc
  package.json
  prettier.config.js
  tailwind.config.js
  yarn.lock
Labels: Status: Completed, Priority: Medium, Type: Enhancement, Category: Frontend(JS CSS)

#51 fest: Mypage UI publishing
  src/app/my-page/delete/page.tsx
  src/app/my-page/history/page.tsx
  src/app/my-page/page.tsx
  src/app/my-page/qna/page.tsx
  src/components/myPage/MyAccountSetting.tsx
  src/components/myPage/MyPageAll.tsx
  src/components/myPage/MyPageNav.tsx
Labels: Status: In Progress, Priority: Medium, Type: Enhancement, Category: Frontend(JS CSS)

#52 에셋 상세페이지 리뷰 탭
  public/icons/emptyStar.svg
  public/icons/filledStar.svg
  src/components/assetDetail/AssetDetail.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assetDetail/AssetDetailNav.tsx
  src/components/assetDetail/AssetDetailReview.tsx
  src/components/assetDetail/AssetDetailWishlist.tsx
  src/components/assetDetail/CreateReview.tsx
  src/components/common/Drawer.tsx
  src/components/common/Star.tsx
Labels: Priority: Medium

#53 feat: layout UI 및 기능
  public/icons/chevronDownBlue.svg
  public/icons/tag.svg
  public/logo-footer.svg
  src/app/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/SideNav/Category.tsx
  src/components/common/SideNav/SideNavList.tsx
  src/components/common/SideNav/Tags.tsx
  src/components/common/SideNav/index.tsx
  src/data/category.json
  src/interface/category.ts
  src/store/store.ts
  src/store/tagSlice.tsx
  tailwind.config.js
Labels: Status: In Progress, Priority: High, Type: Enhancement, Category: Frontend(JS CSS)

#59 feat: 장바구니 UI
  public/icons/checkboxOff.svg
  public/icons/checkboxOn.svg
  public/icons/chevronRight-dis.svg
  public/icons/coupon-dis.svg
  public/image.svg
  src/app/cart/page.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartTable.tsx
  src/styles/globals.css
  src/utils/formatPrice.ts
  tailwind.config.js
Labels: Status: Available, Status: In Progress, Priority: High, Category: Frontend(JS CSS)

#62 feat: API 파일 소스트리 경로 변경
  src/api/auth.ts
  src/api/axios.ts
  src/api/interface/auth.ts
  src/api/interface/category.ts
  src/api/interface/payment.ts
  src/api/service/assets.ts
  src/api/service/category.ts
  src/api/service/payments.ts
Labels: Status: Completed, Priority: Medium, Type: Enhancement, Category: Backend(API DB), Category: Frontend(JS CSS)

#63 feat: api 소스트리 변경에 따른 컴포넌트 import경로 반영
  src/app/page.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assetDetail/AssetDetailReview.tsx
  src/components/assetDetail/AssetDetailWishlist.tsx
  src/components/assets/AssetItem.tsx
  src/components/assets/AssetsList.tsx
  src/components/common/SideNav/Category.tsx
  src/components/common/SideNav/SideNavList.tsx
  src/components/common/SideNav/index.tsx
  src/components/myPage/orderHistory/MyOrderHistoryItem.tsx
  src/components/myPage/orderHistory/MyOrderHistoryList.tsx
  src/interface/category.ts
  src/store/clickedAssetSlice.tsx
Labels: Status: In Progress, Priority: Medium, Type: Enhancement, Category: Backend(API DB), Category: Frontend(JS CSS)

#64 feat: Mypage 2차 퍼블리싱
  src/app/my-page/page.tsx
  src/components/myPage/MyPageAll.tsx
  src/components/myPage/MyPageNav.tsx
  src/components/myPage/orderHistory/MyOrderHistory.tsx
  src/components/myPage/orderHistory/calendar/MyOrderCalendar.tsx
  src/components/myPage/orderHistory/orderHistoryDetail/MyOrderDetail.tsx
  src/components/myPage/setting/AccountDelete.tsx
  src/components/myPage/setting/MyAccountSetting.tsx
Labels: Status: In Progress, Priority: Medium, Type: Enhancement, Category: Frontend(JS CSS)

#65 feat: :sparkles: 마이에셋-주문내역 조회용 캘린더 ui 퍼블리싱
  src/components/myPage/orderHistory/calendar/MyOrderCalendar.module.css
  src/components/myPage/orderHistory/calendar/MyOrderCalendar.tsx
  src/styles/globals.css
Labels: Status: In Progress, Priority: Medium, Type: Enhancement, Category: Frontend(JS CSS)

#69 feat: 로그인 기능 구현
  package.json
  src/api/axios.ts
  src/api/interface/auth.ts
  src/api/interface/index.ts
  src/api/service/auth.ts
  src/components/assetDetail/AssetDetail.tsx
  src/components/assetDetail/AssetDetailAddCart.tsx
  src/components/common/Drawer.tsx
  src/components/common/Star.tsx
  src/components/login/Login.tsx
  src/components/myPage/MyPageAll.tsx
  src/components/myPage/orderHistory/MyOrderHistory.tsx
  src/hooks/useGetAssets.ts
  src/hooks/useLogin.ts
  src/hooks/useUser.ts
  src/reactQuery/Provider.tsx
  src/styles/globals.css
  src/utils/token.ts
  yarn.lock
Labels: Status: Completed, Priority: High, Priority: Medium, Type: Enhancement, Category: Backend(API DB)

#72 feat: 페이지네이션 컴포넌트 구현
  src/api/interface/asset.ts
  src/api/interface/index.ts
  src/api/service/asset.ts
  src/api/service/assets.ts
  src/api/service/auth.ts
  src/app/page.tsx
  src/components/assetDetail/AssetDetailAddCart.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assetDetail/AssetDetailReview.tsx
  src/components/assets/AssetItem.tsx
  src/components/assets/AssetsList.tsx
  src/components/assets/IndividualAsset.tsx
  src/components/common/Layout.tsx
  src/components/common/PaginationButton.tsx
  src/components/myPage/orderHistory/MyOrderHistoryItem.tsx
  src/components/myPage/orderHistory/MyOrderHistoryList.tsx
  src/hooks/useGetAssets.ts
  src/hooks/useLogin.ts
  src/store/clickedAssetSlice.tsx
Labels: Priority: Medium

#73 feat: Signup 기능 구현 완료
  package.json
  src/api/interface/auth.ts
  src/api/service/auth.ts
  src/app/signup/page.tsx
  src/components/common/Header.tsx
  src/components/logout/Logout.tsx
  src/components/signup/SignUp.tsx
  src/components/signup/TermsModal.tsx
  src/hooks/useSignUp.ts
  src/styles/globals.css
  yarn.lock
Labels: Status: Completed, Priority: High, Type: Enhancement, Category: Backend(API DB)

#76 feat: payment UI
  public/icons/payment-kakaoPay.svg
  public/icons/payment-kg.svg
  public/icons/radioOff.svg
  public/icons/radioOn.svg
  src/app/cart/page.tsx
  src/app/payment/complete/page.tsx
  src/app/payment/page.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartTable.tsx
  src/components/common/CustomInput.tsx
  src/components/common/Title.tsx
  src/components/payment/OrderInfo.tsx
  src/components/payment/PaymentInfo.tsx
  src/components/payment/PaymentItem.tsx
  src/components/payment/PaymentMethod.tsx
  src/components/payment/complete/CompleteItem.tsx
  src/components/payment/complete/CompleteTable.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: Status: Available, Priority: High, Category: Frontend(JS CSS)

#77 fix: 로그인 기능 오류 수정
  public/icons/heart.svg
  public/icons/heartFill.svg
  src/api/service/auth.ts
  src/app/page.tsx
  src/components/assetDetail/AssetDetailAddCart.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assets/AssetItem.tsx
  src/components/common/WishlistButton.tsx
  src/hooks/useLogin.ts
  tailwind.config.js
Labels: Priority: Medium, Type: Bug

#81 feat: 1차 QA를 위한 병합작업 2차
  package.json
  public/icons/heart.svg
  public/icons/heartFill.svg
  public/icons/payment-kakaoPay.svg
  public/icons/payment-kg.svg
  public/icons/radioOff.svg
  public/icons/radioOn.svg
  src/api/interface/auth.ts
  src/api/service/auth.ts
  src/app/cart/page.tsx
  src/app/page.tsx
  src/app/payment/complete/page.tsx
  src/app/payment/page.tsx
  src/app/signup/page.tsx
  src/components/assetDetail/AssetDetailAddCart.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assets/AssetItem.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartTable.tsx
  src/components/common/CustomCheckbox.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Title.tsx
  src/components/common/WishlistButton.tsx
  src/components/logout/Logout.tsx
  src/components/payment/OrderInfo.tsx
  src/components/payment/PaymentInfo.tsx
  src/components/payment/PaymentItem.tsx
  src/components/payment/PaymentMethod.tsx
  src/components/payment/complete/CompleteItem.tsx
  src/components/payment/complete/CompleteTable.tsx
  src/components/signup/SignUp.tsx
  src/components/signup/TermsModal.tsx
  src/hooks/useLogin.ts
  src/hooks/useSignUp.ts
  src/styles/globals.css
  src/utils/token.ts
  tailwind.config.js
  yarn.lock
Labels: Type: Enhancement

#84 feat: :sparkles: customCheckbox size 변경
  src/components/common/CustomCheckbox.tsx
Labels: Status: Available, Priority: Medium, Category: Frontend(JS CSS)

#85 feat: auth 관련 페이지 수정
  public/loading.gif
  src/api/interface/auth.ts
  src/api/service/auth.ts
  src/app/loading.tsx
  src/app/login/change/page.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/login/Login.tsx
  src/components/login/change/Chage.tsx
  src/components/signup/SignUp.tsx
  src/components/signup/TermsModal.tsx
  src/hooks/useSignUp.ts
Labels: Priority: High, Type: Bug, Type: Enhancement, Category: Backend(API DB)

#86 feat: 리뷰 보기 기능
  .gitignore
  src/api/axios.ts
  src/api/interface/review.ts
  src/api/service/review.ts
  src/components/assetDetail/AssetDetailReview.tsx
  src/components/assetDetail/ReviewItem.tsx
  src/components/assetDetail/ReviewList.tsx
  src/hooks/useReview.ts
Labels: Priority: Medium

#87 feat: 1차 QA를 위한 Develop 병합 3차
  .gitignore
  public/loading.gif
  src/api/axios.ts
  src/api/interface/auth.ts
  src/api/interface/review.ts
  src/api/service/auth.ts
  src/api/service/review.ts
  src/app/loading.tsx
  src/app/login/change/page.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/assetDetail/AssetDetailReview.tsx
  src/components/assetDetail/ReviewItem.tsx
  src/components/assetDetail/ReviewList.tsx
  src/components/common/CustomCheckbox.tsx
  src/components/login/Login.tsx
  src/components/login/change/Chage.tsx
  src/components/signup/SignUp.tsx
  src/components/signup/TermsModal.tsx
  src/hooks/useReview.ts
  src/hooks/useSignUp.ts
Labels: Type: Enhancement

#90 feat: Auth관련 페이지 기능 수정 및 추가
  public/next.svg
  public/vercel.svg
  src/api/interface/auth.ts
  src/api/service/auth.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/login/change/page.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/common/AuthContainer.tsx
  src/components/login/Login.tsx
  src/components/login/change/Chage.tsx
  src/components/login/change/Change.tsx
  src/components/signup/SignUp.tsx
  src/hooks/useSignUp.ts
Labels: Status: In Progress, Priority: High, Type: Enhancement, Category: Backend(API DB), Category: Frontend(JS CSS)

#91 feat: 디테일 페이지 기능 수정 및 추가
  public/icons/star.svg
  src/api/interface/asset.ts
  src/api/interface/review.ts
  src/api/service/asset.ts
  src/api/service/review.ts
  src/app/page.tsx
  src/components/assetDetail/AssetDetail.tsx
  src/components/assetDetail/AssetDetailAddCart.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assetDetail/AssetDetailReview.tsx
  src/components/assetDetail/CreateReview.tsx
  src/components/assetDetail/ReviewItem.tsx
  src/components/assetDetail/ReviewList.tsx
  src/components/assets/AssetItem.tsx
  src/components/assets/AssetList.tsx
  src/components/assets/AssetTags.tsx
  src/components/assets/IndividualAsset.tsx
  src/components/common/Rating.tsx
  src/components/common/Star.tsx
  src/components/common/WishlistButton.tsx
  src/components/common/WriteRating.tsx
  src/components/common/icon/Stars.tsx
  src/hooks/useAssetDetail.ts
  src/hooks/useLogin.ts
  src/hooks/usePostReview.ts
  src/hooks/useReview.ts
  src/store/clickedAssetSlice.tsx
  src/store/store.ts
  src/store/userSlice.tsx
  src/styles/globals.css
  src/utils/formatRating.ts
Labels: Priority: Medium

#95 fix: 리뷰 기능 구현 수정
  src/api/interface/review.ts
  src/api/service/review.ts
  src/components/assetDetail/AssetDetailNav.tsx
  src/components/assetDetail/AssetDetailReview.tsx
  src/components/assetDetail/ReviewItem.tsx
  src/components/assetDetail/ReviewList.tsx
  src/components/assetDetail/ReviewMenu.tsx
  src/components/common/SideNav/SideNavList.tsx
  src/hooks/usePostReview.ts
Labels: Status: In Progress, Priority: High, Type: Enhancement, Category: Backend(API DB), Category: Frontend(JS CSS)

#96 feat: 5차 merge for QA
  src/api/interface/review.ts
  src/api/service/review.ts
  src/components/assetDetail/AssetDetailNav.tsx
  src/components/assetDetail/AssetDetailReview.tsx
  src/components/assetDetail/ReviewItem.tsx
  src/components/assetDetail/ReviewList.tsx
  src/components/assetDetail/ReviewMenu.tsx
  src/components/common/SideNav/SideNavList.tsx
  src/hooks/usePostReview.ts
Labels: Priority: High, Type: Enhancement

#97 feat: 리뷰 수정, 리뷰 삭제 기능 구현
  src/api/interface/review.ts
  src/api/service/review.ts
  src/components/assetDetail/CreateReview.tsx
  src/components/assetDetail/ReviewItem.tsx
  src/components/assetDetail/ReviewList.tsx
  src/components/assetDetail/ReviewMenu.tsx
  src/components/common/Rating.tsx
  src/components/common/WriteRating.tsx
  src/hooks/usePostReview.ts
  src/store/clickedReviewSlice.tsx
  src/store/store.ts
Labels: Status: In Progress, Priority: High, Type: Enhancement, Category: Backend(API DB)

#98 feat: 리뷰기능 추가 병합
  src/api/interface/review.ts
  src/api/service/review.ts
  src/components/assetDetail/CreateReview.tsx
  src/components/assetDetail/ReviewItem.tsx
  src/components/assetDetail/ReviewList.tsx
  src/components/assetDetail/ReviewMenu.tsx
  src/components/common/Rating.tsx
  src/components/common/WriteRating.tsx
  src/hooks/usePostReview.ts
  src/store/clickedReviewSlice.tsx
  src/store/store.ts
Labels: Type: Enhancement

#100 test: userId저장
  src/api/interface/auth.ts
  src/api/interface/payment.ts
  src/api/service/auth.ts
  src/api/service/myPage.ts
  src/app/my-page/orderHistory/[slug]/page.tsx
  src/components/myPage/orderHistory/MyOrderHistory.tsx
  src/components/myPage/orderHistory/MyOrderHistoryItem.tsx
  src/components/myPage/orderHistory/MyOrderHistoryList.tsx
  src/components/myPage/orderHistory/OrderHistoryDrawer.tsx
  src/components/myPage/orderHistory/orderHistoryDetail/MyOrderDetail.tsx
  src/components/myPage/setting/AccountDelete.tsx
  src/components/myPage/setting/MyAccountSetting.tsx
  src/hooks/useLogin.ts
  src/hooks/useMyPage.ts
  src/hooks/useUser.ts
  src/store/clickedOrderHistorySlice.tsx
  src/store/orderHistoryDetailSlice.tsx
  src/store/orderHistoryStore.ts
Labels: Category: Test

#102 feat: cart Logic
  src/api/interface/cart.ts
  src/api/service/cart.ts
  src/app/cart/page.tsx
  src/components/cart/Cart.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartTable.tsx
  src/components/common/CustomCheckbox.tsx
  src/components/common/header/Header.tsx
  src/store/cartSlice.tsx
  src/store/store.ts
Labels: Status: Available, Priority: High, Category: Frontend(JS CSS)

#103 feat: 장바구니, 마이페이지 기능추가 병합
  src/api/interface/auth.ts
  src/api/interface/cart.ts
  src/api/interface/payment.ts
  src/api/service/auth.ts
  src/api/service/cart.ts
  src/api/service/myPage.ts
  src/app/cart/page.tsx
  src/app/my-page/orderHistory/[slug]/page.tsx
  src/components/cart/Cart.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartTable.tsx
  src/components/common/CustomCheckbox.tsx
  src/components/common/header/Header.tsx
  src/components/myPage/orderHistory/MyOrderHistory.tsx
  src/components/myPage/orderHistory/MyOrderHistoryItem.tsx
  src/components/myPage/orderHistory/MyOrderHistoryList.tsx
  src/components/myPage/orderHistory/OrderHistoryDrawer.tsx
  src/components/myPage/orderHistory/orderHistoryDetail/MyOrderDetail.tsx
  src/components/myPage/setting/AccountDelete.tsx
  src/components/myPage/setting/MyAccountSetting.tsx
  src/hooks/useLogin.ts
  src/hooks/useMyPage.ts
  src/hooks/useUser.ts
  src/store/cartSlice.tsx
  src/store/clickedOrderHistorySlice.tsx
  src/store/orderHistoryDetailSlice.tsx
  src/store/orderHistoryStore.ts
  src/store/store.ts
Labels: Type: Enhancement

#104 feat: 카테고리 기능 구현
  src/api/interface/category.ts
  src/api/service/category.ts
  src/api/service/myPage.ts
  src/app/cart/page.tsx
  src/app/categories/[slug]/page.tsx
  src/app/categories/page.tsx
  src/app/category/[slug]/page.tsx
  src/app/category/page.tsx
  src/app/my-page/orderHistory/page.tsx
  src/app/my-page/page.tsx
  src/app/page.tsx
  src/components/assetDetail/ReviewItem.tsx
  src/components/cart/Cart.tsx
  src/components/cart/CartTable.tsx
  src/components/common/Layout.tsx
  src/components/common/Rating.tsx
  src/components/common/SideNav/Category.tsx
  src/components/common/SideNav/CategoryAsset.tsx
  src/components/common/SideNav/CategoryItem.tsx
  src/components/common/SideNav/CategoryList.tsx
  src/components/common/SideNav/SideNav.tsx
  src/components/common/SideNav/SideNavList.tsx
  src/components/common/SideNav/index.tsx
  src/store/categorySlice.tsx
  src/store/setSelectedCategory.tsx
  src/store/store.ts
  yarn.lock
Labels: Priority: Medium

#114 feat: :sparkles: 내에셋 UI 퍼블리싱
  src/app/my-assets/page.tsx
  src/components/myAsset/MyAsset.tsx
  src/components/myAsset/MyAssetItem.tsx
  src/components/myAsset/MyAssetList.tsx
Labels: Priority: High, Category: Frontend(JS CSS)

#115 feat: 배포 이슈 후 첫 main 병합 Dev
  src/app/my-assets/page.tsx
  src/components/myAsset/MyAsset.tsx
  src/components/myAsset/MyAssetItem.tsx
  src/components/myAsset/MyAssetList.tsx
Labels: Category: Test

#117 feat: :sparkles: 마이페이지: 주문내역 필터링, 필터에 따른 주문내역 출력, 상세 에셋 Drawer 추가 로직 필요
  src/api/interface/myPage.ts
  src/api/interface/payment.ts
  src/api/service/myPage.ts
  src/app/loading.tsx
  src/app/my-page/page.tsx
  src/components/myPage/orderHistory/MyOrderHistory.tsx
  src/components/myPage/orderHistory/MyOrderHistoryItem.tsx
  src/components/myPage/orderHistory/calendar/MyOrderCalendar.tsx
  src/components/myPage/orderHistory/orderHistoryDetail/MyOrderDetail.tsx
  src/components/myPage/setting/AccountDelete.tsx
  src/hooks/useMyPage.ts
Labels: Status: In Progress, Priority: High, Type: Enhancement, Category: Backend(API DB), Category: Frontend(JS CSS)

#118 feat: :sparkles: 위시리스트 UI 퍼블리싱
  next.config.js
  public/icons/cartPlusBlue.svg
  public/icons/trashBlue.svg
  src/app/wishlist/page.tsx
  src/components/common/icon/Icon.tsx
  src/components/wishList/Button.tsx
  src/components/wishList/IconButton.tsx
  src/components/wishList/TableHeader.tsx
  src/components/wishList/TableItem.tsx
  src/components/wishList/WishlistContainer.tsx
Labels: Priority: Medium, Type: Enhancement, Category: Frontend(JS CSS)

#119 feat: 마이페이지, 위시리스트 병합
  next.config.js
  public/icons/cartPlusBlue.svg
  public/icons/trashBlue.svg
  src/api/interface/myPage.ts
  src/api/interface/payment.ts
  src/api/service/myPage.ts
  src/app/loading.tsx
  src/app/my-page/page.tsx
  src/app/wishlist/page.tsx
  src/components/common/icon/Icon.tsx
  src/components/myPage/orderHistory/MyOrderHistory.tsx
  src/components/myPage/orderHistory/MyOrderHistoryItem.tsx
  src/components/myPage/orderHistory/calendar/MyOrderCalendar.tsx
  src/components/myPage/orderHistory/orderHistoryDetail/MyOrderDetail.tsx
  src/components/myPage/setting/AccountDelete.tsx
  src/components/wishList/Button.tsx
  src/components/wishList/IconButton.tsx
  src/components/wishList/TableHeader.tsx
  src/components/wishList/TableItem.tsx
  src/components/wishList/WishlistContainer.tsx
  src/hooks/useMyPage.ts
Labels: Category: Frontend(JS CSS)

#120 feat: 장바구니 로직
  src/api/interface/cart.ts
  src/api/service/cart.ts
  src/app/cart/page.tsx
  src/components/cart/Cart.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartTable.tsx
  src/utils/cartUtils.ts
Labels: Status: Available, Priority: High, Category: Frontend(JS CSS)

#123 feat: 결제 로직
  src/api/interface/payment.ts
  src/api/service/payments.ts
  src/app/payment/page.tsx
  src/components/payment/OrderInfo.tsx
  src/components/payment/Payment.tsx
  src/components/payment/PaymentInfo.tsx
  src/components/payment/PaymentItem.tsx
  src/components/payment/PaymentMethod.tsx
  src/styles/globals.css
  src/utils/paymentUtils.ts
  tailwind.config.js
Labels: Status: In Progress, Status: Review Needed, Priority: High, Category: Frontend(JS CSS)

#124 feat: 장바구니 병합
  src/api/interface/cart.ts
  src/api/interface/payment.ts
  src/api/service/cart.ts
  src/api/service/payments.ts
  src/app/cart/page.tsx
  src/app/payment/page.tsx
  src/components/cart/Cart.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartInfo.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartTable.tsx
  src/components/payment/OrderInfo.tsx
  src/components/payment/Payment.tsx
  src/components/payment/PaymentInfo.tsx
  src/components/payment/PaymentItem.tsx
  src/components/payment/PaymentMethod.tsx
  src/styles/globals.css
  src/utils/cartUtils.ts
  src/utils/paymentUtils.ts
  tailwind.config.js
Labels: Type: Enhancement, Category: Backend(API DB), Category: Frontend(JS CSS)

#125 feat: login, logout 로직추가
  public/icons/download.svg
  src/api/interface/myAsset.ts
  src/api/service/myAsset.ts
  src/components/common/DropDown.tsx
  src/components/logout/Logout.tsx
  src/components/myAsset/MyAsset.tsx
  src/components/myAsset/MyAssetItem.tsx
  src/components/myAsset/MyAssetList.tsx
  src/hooks/useGetMyAssets.ts
  src/hooks/useLogin.ts
  src/store/clickedMyAssetSlice.tsx
Labels: Category: Frontend(JS CSS)

#126 feat: 내에셋, 로그인 기능 추가 병합
  public/icons/download.svg
  src/api/interface/myAsset.ts
  src/api/service/myAsset.ts
  src/components/common/DropDown.tsx
  src/components/logout/Logout.tsx
  src/components/myAsset/MyAsset.tsx
  src/components/myAsset/MyAssetItem.tsx
  src/components/myAsset/MyAssetList.tsx
  src/hooks/useGetMyAssets.ts
  src/hooks/useLogin.ts
  src/store/clickedMyAssetSlice.tsx
Labels: Priority: High, Type: Enhancement, Category: Backend(API DB), Category: Frontend(JS CSS)

#128 feat: Asset 기능 추가 병합
  next.config.js
  package.json
  src/api/interface/asset.ts
  src/api/interface/category.ts
  src/api/service/category.ts
  src/app/categories/[...slug]/page.tsx
  src/app/categories/[slug]/page.tsx
  src/app/categories/page.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assets/AssetItem.tsx
  src/components/common/Layout.tsx
  src/components/common/SideNav/Category.tsx
  src/components/common/SideNav/CategoryAsset.tsx
  src/components/common/SideNav/CategoryItem.tsx
  src/components/common/SideNav/CategoryList.tsx
  src/components/common/SideNav/SideNav.tsx
  src/components/common/SideNav/SideNavList.tsx
  src/components/common/SideNav/Tags.tsx
  src/components/common/SideNav/index.tsx
  src/components/myPage/orderHistory/calendar/MyOrderCalendar.tsx
  src/data/category.json
  src/store/categorySlice.tsx
  src/store/store.ts
  yarn.lock
Labels: Priority: High, Type: Enhancement, Category: Backend(API DB)

#131 feat: 카테고리 클릭 시 해당 에셋 보이기
  src/api/service/asset.ts
  src/app/categories/[...slug]/page.tsx
  src/app/page.tsx
  src/components/assetDetail/AssetDetailContent.tsx
  src/components/assets/CategoryByAsset.tsx
  src/components/assets/IndividualAsset.tsx
  src/components/common/Rating.tsx
  src/components/myAsset/MyAsset.tsx
  src/data/category.json
  src/hooks/useGetAssets.ts
Labels: Priority: High, Type: Enhancement, Category: Backend(API DB)
